### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by Adrian-Nonn** [MohitSethi99/ArcGameEngine#13]
If I go to full screen the window is slightly bigger than the screen so the borders get cut away and I don't know how to fix that.
![Bug](https://user-images.githubusercontent.com/118981463/207159791-b67743a1-4a8d-4282-b9d8-dc4a9b3bed41.PNG)

You can see it on the stats panel bottom left.

**Comment by MohitSethi99** [comment]
Fixed: https://github.com/MohitSethi99/ArcGameEngine/commit/b68282850d4b395319296d6d708c80b0749de5fc
